Task 7 - POST complete
Souness1982/Stephen-Souness---Back-End-Project pull request #7
Opened 2022-11-17 15:47 UTC by Souness1982

2022-11-17 16:19 UTC, yangalexyangg requested changes
Nice work but you need to add more error handling for when the username is not found and when there is a missing required field in the body

2022-11-17 16:19 UTC, yangalexyangg commented on __tests__/app.test.js
> +          review_id: expect.any(Number),
we know the review id is 3

2022-11-17 16:33 UTC, souste commented on __tests__/app.test.js
> +          review_id: expect.any(Number),
Thanks Alex I will make the changes.

2022-11-18 15:11 UTC, hevmag commented on model/model.js
> +    console.log(result.rows[0]);
remove console.log before merge

2022-11-18 15:12 UTC, hevmag approved these changes
Nice work Stephen! Looks good to me, just give it a scan and make sure to remove any console.logs and any unnecessary comments before merging

2022-11-18 15:16 UTC, souste commented on model/model.js
> +    console.log(result.rows[0]);
Thanks Hev, I'll make the changes!

2022-11-18 15:18 UTC, merged